import calculateReward from "./Main.js";
r1()
function r1() {
    console.log('Kết quả kiểm thử bảng quyết định')
    console.log('Kết quả case 1: ',calculateReward('Nhân viên', 0.2))
    console.log('Kết quả case 2: ',calculateReward('Nhân viên', 0.6))
    console.log('Kết quả case 3: ',calculateReward('Nhân viên', 0.9))
    console.log('Kết quả case 4: ',calculateReward('Nhân viên', -0.1))
    console.log('Kết quả case 5: ',calculateReward('Nhân viên', 1.1))
    console.log('Kết quả case 6: ',calculateReward('Nhân viên', 1.6))
    console.log('Kết quả case 7: ',calculateReward('Thực tập', 0.2))
    console.log('Kết quả case 8: ',calculateReward('Thực tập', 0.6))
    console.log('Kết quả case 9: ',calculateReward('Thực tập', 0.95))
    console.log('Kết quả case 10: ',calculateReward('Thực tập', -0.2))
    console.log('Kết quả case 11: ',calculateReward('Thực tập', 1.2))
    console.log('Kết quả case 12: ',calculateReward('Thực tập', 1.7))
    console.log('Kết quả case 13: ',calculateReward('Quản lí', 0.2))
    console.log('Kết quả case 14: ',calculateReward('Quản lí', 0.6))
    console.log('Kết quả case 15: ',calculateReward('Quản lí', 0.85))
    console.log('Kết quả case 16: ',calculateReward('Quản lí', -0.1))
    console.log('Kết quả case 17: ',calculateReward('Quản lí', 1.15))
    console.log('Kết quả case 18: ',calculateReward('Quản lí', 1.8))
    console.log('Kết quả case 19: ',calculateReward('Khác', 0.2))
    console.log('Kết quả case 20: ',calculateReward('Khác', 0.6))
    console.log('Kết quả case 21: ',calculateReward('Khác', 0.85))
    console.log('Kết quả case 22: ',calculateReward('Khác', -0.1))
    console.log('Kết quả case 23: ',calculateReward('Khác', 1.15))
    console.log('Kết quả case 24: ',calculateReward('Khác', 1.8))
}