import calculateReward from "./Main.js";
r1()
function r1() {
    console.log('Kết quả kiểm thử biên')
    console.log('Kết quả case 1: ',calculateReward('Nhân viên', 0))
    console.log('Kết quả case 2: ',calculateReward('Nhân viên', 1))
    console.log('Kết quả case 3: ',calculateReward('Nhân viên', 0.001))
    console.log('Kết quả case 4: ',calculateReward('Nhân viên', 1.49))
    console.log('Kết quả case 5: ',calculateReward('Nhân viên', -0.001))
    console.log('Kết quả case 6: ',calculateReward('Nhân viên', 1.51))
    console.log('Kết quả case 7: ',calculateReward('Nhân viên', 0.75))
    console.log('Kết quả case 8: ',calculateReward('Thực tập', 0))
    console.log('Kết quả case 9: ',calculateReward('Thực tập', 1))
    console.log('Kết quả case 10: ',calculateReward('Thực tập', 0.001))
    console.log('Kết quả case 11: ',calculateReward('Thực tập', 1.49))
    console.log('Kết quả case 12: ',calculateReward('Thực tập', -0.001))
    console.log('Kết quả case 13: ',calculateReward('Thực tập', 1.51))
    console.log('Kết quả case 14: ',calculateReward('Thực tập', 0.75))
    console.log('Kết quả case 15: ',calculateReward('Quản lí', 0))
    console.log('Kết quả case 16: ',calculateReward('Quản lí', 1))
    console.log('Kết quả case 17: ',calculateReward('Quản lí', 0.001))
    console.log('Kết quả case 18: ',calculateReward('Quản lí', 1.49))
    console.log('Kết quả case 19: ',calculateReward('Quản lí', -0.001))
    console.log('Kết quả case 20: ',calculateReward('Quản lín', 1.51))
    console.log('Kết quả case 21: ',calculateReward('Quản lí', 0.75))
    console.log('Kết quả case 22: ',calculateReward('Khác', 0))
    console.log('Kết quả case 23: ',calculateReward('Khác', 1))
    console.log('Kết quả case 24: ',calculateReward('Khác', 0.001))
    console.log('Kết quả case 25: ',calculateReward('Khác', 1.49))
    console.log('Kết quả case 26: ',calculateReward('Khác', -0.001))
    console.log('Kết quả case 27: ',calculateReward('Khác', 1.51))
    console.log('Kết quả case 28: ',calculateReward('Khác', 0.75))
  
}